workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_connect
      vars:
        APP_ID: "com.nerdherd.app"
    integrations:
      app_store_connect: codemagic-api-key
    signing:
      ios:
        app_store_connect: codemagic
        distribution_type: app_store
        bundle_identifier: com.nerdherd.app
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages get
      - name: Install pods
        script: |
          find . -name "Podfile" -exec dirNAME={} \; | xargs -n 1 pod install --project-directory
      - name: Build iOS Archive
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - "*.dSYM.zip"
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
