-- Import Course Data from Scraper Output
-- Run this AFTER migrate_real_courses.sql

-- This script imports course data generated by scripts/scrape_courses.py
-- You can either:
-- 1. Use Supabase Dashboard to import courses.json directly
-- 2. Or use this SQL template to insert courses manually

-- ============================================================================
-- SAMPLE: Insert UH Computer Science Courses
-- ============================================================================

DO $$
DECLARE
  uh_id UUID;
  cosc_dept_id UUID;
BEGIN
  -- Get UH university ID
  SELECT id INTO uh_id FROM universities WHERE short_name = 'UH';
  
  -- Get Computer Science department ID
  SELECT id INTO cosc_dept_id FROM departments 
  WHERE university_id = uh_id AND code = 'COSC';

  -- Insert courses
  INSERT INTO courses (university_id, department_id, course_code, course_number, title, credits, description) VALUES
    (uh_id, cosc_dept_id, 'COSC 1301', '1301', 'Introduction to Computing', 3, 'Introduction to Computing - Computer Science course at University of Houston'),
    (uh_id, cosc_dept_id, 'COSC 1336', '1336', 'Programming Fundamentals I', 3, 'Programming Fundamentals I - Computer Science course at University of Houston'),
    (uh_id, cosc_dept_id, 'COSC 1437', '1437', 'Programming Fundamentals II', 4, 'Programming Fundamentals II - Computer Science course at University of Houston'),
    (uh_id, cosc_dept_id, 'COSC 2336', '2336', 'Programming Fundamentals III', 3, 'Programming Fundamentals III - Computer Science course at University of Houston'),
    (uh_id, cosc_dept_id, 'COSC 2425', '2425', 'Computer Organization', 4, 'Computer Organization - Computer Science course at University of Houston'),
    (uh_id, cosc_dept_id, 'COSC 3320', '3320', 'Data Structures', 3, 'Data Structures - Computer Science course at University of Houston'),
    (uh_id, cosc_dept_id, 'COSC 3340', '3340', 'Introduction to Automata and Computability Theory', 3, 'Introduction to Automata and Computability Theory - Computer Science course at University of Houston'),
    (uh_id, cosc_dept_id, 'COSC 3380', '3380', 'Database Systems', 3, 'Database Systems - Computer Science course at University of Houston'),
    (uh_id, cosc_dept_id, 'COSC 4315', '4315', 'Programming Languages and Paradigms', 3, 'Programming Languages and Paradigms - Computer Science course at University of Houston'),
    (uh_id, cosc_dept_id, 'COSC 4353', '4353', 'Algorithm Design and Analysis', 3, 'Algorithm Design and Analysis - Computer Science course at University of Houston')
  ON CONFLICT (university_id, course_code) DO NOTHING;
  
  RAISE NOTICE 'Inserted UH Computer Science courses';
END $$;

-- ============================================================================
-- RECOMMENDED: Use Supabase Dashboard for Bulk Import
-- ============================================================================

-- Instead of manually inserting all 150+ courses, use the Supabase Dashboard:
-- 1. Go to Table Editor > courses
-- 2. Click "Insert" > "Import data from CSV"
-- 3. Upload scripts/courses.csv
-- 4. Map columns appropriately
-- 5. Import!

-- OR use the Supabase CLI:
-- supabase db push --csv courses.csv

-- ============================================================================
-- Verify Import
-- ============================================================================

-- Check course counts
SELECT 
  u.short_name,
  d.name AS department,
  COUNT(*) AS course_count
FROM courses c
JOIN universities u ON c.university_id = u.id
JOIN departments d ON c.department_id = d.id
GROUP BY u.short_name, d.name
ORDER BY u.short_name, d.name;

-- Test search function
SELECT * FROM search_courses('programming');
SELECT * FROM search_courses('math', 'UH');
SELECT * FROM search_courses('biology', 'HCC');
